In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns; sns.set()  # for plot styling
import numpy as np
import pandas as pd

In [2]:
from sklearn.cluster import KMeans
from collections import Counter, defaultdict
from scipy.cluster.vq import kmeans,vq
from scipy import stats


In [5]:
mobile= pd.read_csv('cluster.csv')

In [6]:
mobile

villagecodes  Television  Mobile  Other than perm      P_LIT %  \
0                0        48.6    56.4             12.0  65.10148103   
1                0        39.7    54.6             14.4  65.10148103   
2           597114        56.4    47.9              1.9  63.15531602   
3           597115        59.1    64.2              1.1  71.40707299   
4           597116        49.7    66.8              0.5  63.07471264   
5           597117        58.1    63.3              0.0  70.85330777   
6           597118        56.9    52.5              2.5  69.38540122   
7           597119        41.0    53.8              0.7  66.18421053   
8           597120        59.9    47.6              1.1  68.35156886   
9           597121        47.1    64.3              2.7  66.11909651   
10          597122        52.4    56.1              1.8  68.91684566   
11          597123        55.2    50.0              4.1   67.1129833   
12          597124        67.5    64.5              0.0  71.37096774   
13          597125        55.1    57.5              2.4  67.77739998   
14          597126        60.3    59.4              0.4  73.81930185   
15          597127        54.4    53.9              0.9  66.32548618   
16          597128        56.1    67.1              1.6  67.91701245   
17          597129        53.1    56.2              4.2   69.7019479   
18          597130        55.4    60.4              0.4  71.18566176   
19          597131        42.2    61.7              2.0   66.3107511   
20          597132        50.1    32.0              0.6  67.06680585   
21          597133        49.2    50.6              2.3  62.11323662   
22          597134        60.8    80.5              2.1  76.11163671   
23          597135        50.7    46.0              1.6  64.93174061   
24          597136        44.3    49.1              1.7  60.16839378   
25          597137        51.0    55.3              3.2  66.93238043   
26          597138        46.0    57.3              1.1  65.21344233   
27          597139        44.0    55.6              4.9  60.74906367   
28          597140        42.1    34.3              0.6  64.21713442   
29          597141        41.4    54.8              0.3  66.19950536   
...            ...         ...     ...              ...          ...   
1273        598372        38.5    32.5              2.0  61.03795507   
1274        598373        28.5    24.8             14.8  59.09090909   
1275        598374        26.3    40.8              9.2  47.17832957   
1276        598375        37.7    63.8             11.1  48.31160147   
1277        598376        48.1    53.5             15.5  55.23163516   
1278        598377        64.6    63.6              0.0  74.67672414   
1279        598378        30.2    50.0             13.1  52.05855444   
1280        598379        15.0    35.4              6.3  42.40447344   
1281        598380        59.9    34.3             52.6  55.26675787   
1282        598381        16.6    53.1            101.2  53.67734282   
1283        598382        21.4    51.7             20.6  55.13654096   
1284        598383        35.0    60.9             37.6  51.87601958   
1285        598384        35.8    67.4             56.6  56.10068259   
1286        598385        53.8    57.8             55.5   64.6818298   
1287        598386        34.4    23.0             41.8  66.41318124   
1288        598387        45.7    73.0             66.8  61.10828673   
1289        598388        53.2    60.3             79.0  66.91439582   
1290        598389        12.6    66.3             14.8  48.34254144   
1291        598390         8.4    47.1             47.9  46.96699376   
1292        598391        14.2    22.2             71.6  64.90566038   
1293        598392        37.7    65.6             47.6  58.04195804   
1294        598393        30.4    40.6             68.1  52.16251638   
1295        598394        21.2    48.8             19.4  51.23390558   
1296        598395        24.8    52.5        

In [7]:
mob = (mobile['Mobile']).as_matrix()

C:\Users\rachit\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


In [8]:
mob

array([56.4, 54.6, 47.9, ..., 47.4, 67.4, 53.2])

In [9]:
mob1 = mob.reshape(-1,1)

In [10]:
mob1.shape

(1303, 1)

In [11]:
mob1

array([[56.4],
       [54.6],
       [47.9],
       ...,
       [47.4],
       [67.4],
       [53.2]])

In [12]:
km = KMeans(n_clusters=3)
km.fit(mob1.reshape(-1,1))
labels = km.labels_
centroids,_= kmeans(mob1,3)
idx,_=vq(mob1,centroids)
print(centroids)


[[30.69049296]
 [67.95234742]
 [52.73507589]]


In [13]:
print(np.bincount(idx))

[250 429 624]


In [14]:
centroids,_= kmeans(mob1,4)
idx,_=vq(mob1,centroids)
print(centroids)

[[42.73232044]
 [69.9689441 ]
 [56.61070039]
 [17.51142857]]


In [15]:
print(np.bincount(idx))

[362 310 532  99]


In [16]:
centroids,_= kmeans(mob1,5)
idx,_=vq(mob1,centroids)
centroids

array([[15.14659091],
       [50.09660494],
       [38.55263158],
       [59.69927184],
       [71.65498008]])

In [17]:
print(np.bincount(idx))

[ 83 340 227 419 234]


In [19]:
mobile2=mob[(np.abs(stats.zscore(mob)) < 3).all(axis=1)]

AxisError: axis 1 is out of bounds for array of dimension 1

In [17]:
mob2= (mobile2['Mobile']).as_matrix()

C:\Users\rachit\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


In [18]:
mob22 = mob2.reshape(-1,1)

In [19]:
centroids,_= kmeans(mob22,3)
idx,_=vq(mob22,centroids)
centroids

array([[38.69936441],
       [70.49471459],
       [56.7663199 ]])

In [20]:
print(np.bincount(idx))

[424 477 813]


In [21]:
centroids,_= kmeans(mob22,4)
idx,_=vq(mob22,centroids)
centroids

array([[49.11637081],
       [32.11652893],
       [72.14359673],
       [60.38879599]])

In [22]:
print(np.bincount(idx))

[523 217 353 621]


In [23]:
centroids,_= kmeans(mob22,5)
idx,_=vq(mob22,centroids)
centroids

array([[55.55673913],
       [45.49765013],
       [28.94127907],
       [75.40465116],
       [64.2392562 ]])

In [24]:
print(np.bincount(idx))

[473 382 157 209 493]
